version: '3.4'

services:
  p9ys.web:
    image: ccr.ccs.tencentyun.com/wuuu/p9ysweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8001:80"
    container_name: p9ysweb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - default

  p9ys.manage:
    image: ccr.ccs.tencentyun.com/wuuu/p9ysmanage
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8002:80"
    container_name: p9ysmanage
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - default

  p9ys.nginx:
    image: ccr.ccs.tencentyun.com/wuuu/p9ysnginx
    ports:
      - "8080:80"
      - "80:80"
    container_name: p9ysnginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - default
      
networks:
  default:
    external: #容器外部已有的network
      name: custom_bridge